#ifndef DEFS_H
#define DEFS_H

#define HEIGHT 1080
#define WIDTH 1800

#define WHITE 0xFFFFFFFF
#define OFF_WHITE 0xFFFAF9F6
#define GRAY 0xFF808080
#define BLACK 0xFF000000
#define BLUE 0xff86c5d8
#define YELLOW 0xfff1e86e
#define PURPLE 0xffb194d1

#define FPS_DELAY 50
#define MAX_STARS 600

#define BORDER_OFFSET 10
#define BORDER_THICKNESS 3

#define STAR_MIN_X (BORDER_OFFSET + BORDER_THICKNESS)
#define STAR_MAX_X (WIDTH - BORDER_OFFSET - BORDER_THICKNESS)

#define STAR_MIN_Y (BORDER_OFFSET + BORDER_THICKNESS)
#define STAR_MAX_Y (HEIGHT - BORDER_OFFSET - BORDER_THICKNESS)

#endif
